server:
  port: 8002
# mybatis配置
mybatis:
  type-aliases-package: site.whatsblog.pojo
  config-location: classpath:mybatis/mybatis-config.xml
# Spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db02
    username: root
    password: root
#Eureka配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: ${spring.application.name}-8002
    prefer-ip-address: true


info:
  app.name: Whats-Blog-SpringCloud
  company.name: Whats-Blog
